swagger: "2.0"
info:
  version: "1.0.0"
  title: "Photo Social Network API"
paths:
  /api/photos:
    post:
      summary: Upload a photo
      consumes:
        - multipart/form-data
      parameters:
        - name: image
          in: formData
          type: file
          required: true
          description: The JPG image file to be uploaded
      responses:
        200:
          description: Photo uploaded successfully
          schema:
            type: object
            properties:
              imageId:
                type: string
    get:
      summary: List photos
      responses:
        200:
          description: List of photos
          schema:
            type: array
            items:
              $ref: "#/definitions/Photo"
  /api/photos/{photoId}:
    get:
      summary: Get photo details
      parameters:
        - name: photoId
          in: path
          type: string
          required: true
      responses:
        200:
          description: Photo details
          schema:
            $ref: "#/definitions/Photo"
    patch:
      summary: Mark a photo as private
      parameters:
        - name: photoId
          in: path
          type: string
          required: true
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/PhotoPrivacy"
      responses:
        200:
          description: Photo updated successfully
          schema:
            $ref: "#/definitions/Photo"
    delete:
      summary: Delete a photo
      parameters:
        - name: photoId
          in: path
          type: string
          required: true
      responses:
        200:
          description: Photo deleted successfully
definitions:
  Photo:
    type: object
    properties:
      photoId:
        type: string
      imageUrl:
        type: string
      comments:
        type: array
        items:
          $ref: "#/definitions/Comment"
      likes:
        type: integer
      isPrivate:
        type: boolean
  Comment:
    type: object
    properties:
      commentId:
        type: string
      comment:
        type: string
  PhotoPrivacy:
    type: object
    properties:
      isPrivate:
        type: boolean
